# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy app source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose port if necessary (MCP typically communicates via stdio, so not needed)

# Define command to run your app
CMD [ "npm", "start" ]
